config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
    resources :categories do
      collection do
        get 'dashboard'
        # get 'study'
        # get 'team'
      end
        resources :tasks
    end
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks, dependent: :destroy
    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 180}
    validates :description, length: {maximum: 1000}
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
    has_many :users, through: :categories
    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 100}
    validates :description, length: {maximum: 2000}
    validate :due_date_cannot_be_in_the_past

  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "can't be in the past")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy 
  has_many :tasks, through: :categories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        dashboard_categories_path
    end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.valid?
      @category.save
      flash[:notice] = "Category was successfully created!"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully!"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = current_user.categories.all.order(created_at: :desc)
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end
  
  def dashboard
    @tasks = current_user.tasks
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :get_category, only: [ :create, :edit, :update, :destroy, :new ] 

    def show
        @task = Task.find(params[:id])
    end

    def index
        @tasks = Task.order(due_date: :desc)
    end
    
    
    def new
        @task = Task.new
    end

    def create        
        @task = @category.tasks.new(params.require(:task).permit(:name, :description, :due_date))

        if @task.valid? 
            @task.save
            flash[:notice] = "Task created successfully!"
            redirect_to category_path(@category)
        else
            render 'new'
        end
    end

    def edit
        category = Category.find(params[:category_id])
        @task = @category.tasks.find(params[:id])
    end

    def update
        @task = @category.tasks.find(params[:id])
        if @task.valid? 
          @task.update(task_params)
          flash[:notice] = "Task updated successfully!"
          redirect_to @category
        else
          render 'edit'
        end
    end

    def destroy
        category = Category.find(params[:category_id])
        @task = category.tasks.find(params[:id])
        @task.destroy
        redirect_to category_path(category)
    end

    def get_category
        @category = Category.find(params[:category_id])
    end

    private

    def task_params
        params.require(:task).permit(:name, :due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/dashboard.html.erb
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-1 me-5">
      <%= render "partials/sidebar"%>
    </div>
    <div class="col-md-4 ms-3 mt-2">
        <p class="text-center" style="font-size:30px">Tasks for Today</p>
          <table class="table table-warning custom4-5">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Deadline</th>
              </tr>
            </thead>
            <tbody>
              <% @tasks.each do |task| %>
                <% if task.due_date == Date.today %>
                  <tr class="table-active">
                    <td><%= link_to task.name, category_path(task.category_id) %></td>
                    <td><%= task.due_date.strftime("%m/%d") %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
    </div>          
  </div>
</div> <!-- container -->

app/views/categories/edit.html.erb
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-1 me-5">
      <%= render "partials/sidebar"%>
    </div>
    <div class="col-md-4 ms-3">
      <div class="card text-black bg-warning ms-2 mt-2 mb-2 custom3">
        <h4 class="card-header text-decoration">Edit Project</h4>
        <div class="mt-2">
        <%= render "partials/error" %>
          <%= form_with model: @category, local: true do |f| %>
            <div class="form-group ms-2 custom7">
              <p>
                <%= f.text_field :name, placeholder: "Edit Project Title", class: "form-control" %>
              </p>
            </div>

            <div class="form-group ms-2 custom7">
              <p>
                <%= f.text_area :description, placeholder: "Edit Project Description", class: "form-control" %>
              </p>
            </div>

            <p class="ms-2">
            <%= submit_tag("Update Project") %>
            </p>
          <% end %> 
        </div>
      </div>
    </div>
    <div class="col-md-6">
  </div>

app/views/categories/index.html.erb
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-1 me-5">
      <%= render "partials/sidebar"%>
    </div>

    <div class="col-md-10 ms-3 mt-2">
      <div class="row">
        <% @categories.each do |category| %>
            <div class="col-md-3 mb-2 ms-0">
              <div class="card border-warning h-100">  
                <h4 class="card-header text-decoration"><%= category.name%></h4>
                <div class="card-body">
                <p class="card-title"><%= category.description.first(64)%></p> 
              </div>  
              <div class="card-body2 ms-3">
                  <a href="<%= edit_category_path(category) %>"><i class="fas fa-edit" 
                  data-toggle="tooltip" data-placement="bottom" title="Edit Project Details" 
                  style="font-size:16px"></i></a> 
                  <a href="<%= category_path(category) %>"><i class="fas fa-eye" 
                  data-toggle="tooltip" data-placement="bottom" title="View Project Details and Tasks" 
                  style="font-size:16px"></i></a>
                  <%= link_to category_path(category), method: :delete, data: { confirm: 'Are you sure?' } do %>
                                                <i class="fas fa-trash-alt" data-toggle="tooltip" 
                                                data-placement="bottom" title="Delete Project" 
                                                style="font-size:16px"></i><% end %>
                                                
              </div>  
            </div>
          </div>
          <% end %>
      </div><!-- row-->
    </div> <!-- col-10 -->
    <div class="col-md-1">
    </div>
  </div> <!-- row-->
</div> <!-- container-->
  



  

app/views/categories/new.html.erb
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-1 me-5">
      <%= render "partials/sidebar"%>
    </div>
    <div class="col-md-4 ms-3">
      <div class="card text-black bg-warning ms-2 mt-2 mb-2 custom3">
        <h4 class="card-header text-decoration">Create A Project</h4>
        <div class="mt-2">
          <%= render "partials/error" %>
          <%= form_with model: @category, local: true do |f| %>
            <div class="form-group ms-2 custom7">
              <p>
                <%= f.text_field :name, placeholder: "Enter Project Title", class: "form-control" %>
              </p>
            </div>

            <div class="form-group ms-2 custom7">
              <p>
                <%= f.text_area :description, placeholder: "Enter Project Description", class: "form-control" %>
              </p>
            </div>

            <p class="ms-2">
            <%= submit_tag("Create Project") %>
            </p>
          <% end %> 
        </div>
      </div>
    </div>
    <div class="col-md-6">
  </div>

app/views/categories/show.html.erb
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-1 me-5">
      <%= render "partials/sidebar"%>
    </div>
    <div class="col-md-5 ms-3 mt-2">
        <div class="card border-warning">  
            <h4 class="card-header text-decoration"><%= @category.name%></h4>
            <div class="card-body">
                <p class="card-title"><%= @category.description%></p>
            </div>
        </div>        
    </div>
    <div class="col-md-4">
        <p class="text-center" style="font-size:20px">Tasks
                        <a href="<%= new_category_task_path(@category) %>"><i class="far fa-calendar-plus" 
                        data-toggle="tooltip" data-placement="bottom" title="Add a task" 
                        style="font-size:20px"></i></a>
        </p>
        <table class="table table-warning custom4-5">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Deadline</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @category.tasks.order(due_date: :asc).each do |task| %>
              <tr class="table-active">
                <th scope="row"><%= task.name %></th>
                  <td><%= task.due_date.strftime("%m/%d") %></td>
                  <td><a href="<%= edit_category_task_path(@category, task) %>"><i class="fas fa-edit" 
                      data-toggle="tooltip" data-placement="bottom" title="Edit Task" 
                      style="font-size:16px"></i></a>
                      <%= link_to category_task_path(@category, task), method: :delete, data: { confirm: 'Are you sure?' } do %> <i class="fas fa-trash-alt" data-toggle="tooltip" data-placement="bottom" title="Delete Task" style="font-size:16px"></i><% end %></td>              
              </tr>  
            <% end %>
          </tbody>
        </table>
    </div>          
  </div>
</div> <!-- container -->

app/views/home/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 ms-4">
            <%= image_tag("animatedhome.svg", size: "500x500") %>
        </div>
        <div class="col-md-5 mt-5">
            <div style="font-size:50px">Welcome to<h1 class="ms-5" style="font-size:80px">MyProj-<i class="fas fa-check-circle"></i></h1>
            </div>
            <div class="d-grid col-4 mx-5">
                <%= link_to "Get started", new_user_registration_path, class: "btn btn-dark btn-outline-warning" %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/nav" %>
    <%= render "partials/flash" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_error.html.erb
<div class="alert-danger">
  <% if @category.errors.any? %>
    <p class="text-center">
        <ul class="fa-ul">    
            <%@category.errors.full_messages.each do |msg| %>
                <li><i class="fas fa-exclamation-triangle"></i><%= msg %></li> 
            <% end %> 
        </ul>
    </p>
  <% end %>
</div>

app/views/partials/_flash.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <i class="fas fa-check-circle"></i><%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-primary bg-warning mt-1 ms-2 me-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="/home/index"><h1 class="ms-2">MyProj-<i class="fas fa-check-circle"></i> </h1></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class= "d-flex .justify-content-sm-end">
      <div class="collapse navbar-collapse" id="navbarColor02">

      <ul class="navbar-nav me-4" style="font-size: 25px">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Log-out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Log-in", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
            </li>
        <% end %>        
    </div>
  </div>
  </div>

  <div class="footer">
    <%= image_tag("footer2.png") %>
  </div>
</nav>

app/views/partials/_sidebar.html.erb
<div class="btn-group-vertical mt-2 ms-2">
    <a href="/categories/dashboard" class="btn btn-primary custom">Dashboard</a>
    <a href="/categories/new" class="btn btn-primary custom">Create Project</a>
    <a href="/categories" class="btn btn-primary custom">Projects</a>
  </div>

app/views/partials/_task-error.html.erb
<div class="alert-danger w-100">
    <% if @task.errors.any? %>
            <ul class="fa-ul">    
                <%@task.errors.full_messages.each do |msg| %>
                    <li><i class="fas fa-exclamation-triangle"></i><%= msg %></li> 
                <% end %> 
            </ul>
    <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="container container-transparent">
  <div class="alert alert-danger alert-dismissible fade show " role="alert">
    <h4 class="alert-heading mb-4"><i class="fas fa-exclamation-triangle mr-3"></i>   The folowing errors prevent the <%=obj.class.name.downcase%> from being saved</h4>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <hr>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>  
  
    <%end%>
    </ul>
    </div>
  </div>
  <%end%>

app/views/tasks/edit.html.erb
<div class="d-inline-flex p-2">
  <div class="btn-group-vertical mt-2 ms-2 custom5">
    <a href="/categories/dashboard" class="btn btn-primary custom">Dashboard</a>
    <a href="#" class="btn btn-primary custom">Profile</a>
    <a href="/categories/new" class="btn btn-primary custom">Create Project</a>
    <a href="/categories" class="btn btn-primary custom">Projects</a>
  </div>

  
    <div class="card border-warning ms-2 mt-2 mb-2 custom4-5">  
      <h4 class="card-header text-decoration"><%= @category.name %></h4>
    <div class="card-body">
      <p class="card-title"><%= @category.description%></p>
    </div>
    </div>

<div class="card text-black bg-white ms-2 mt-2 mb-2 custom6">
  <h4 class="card-header text-decoration">Edit Task</h4>
  <div class="form-group mt-2 custom4-5">
    <%= form_with scope: :task, model: [ @category, @task ], local: true do |f| %>
      <%= hidden_field_tag :category_id, @category.id %>
      <p class="row custom4-5 ms-2">
        <%= f.text_field :name, placeholder: "Edit Task Name" %>
      </p>
      <p class="row custom4-5 ms-2">
        <%= f.date_field :due_date %>
      </p>
      <p class="ms-2">
      <%= submit_tag("Update Task") %>
      </p>
    <% end %> 
  </div>
</div>

 

app/views/tasks/index.html.erb
<h1> Tasks </h1>

<table>
<% @tasks.each do |task| %>
<tr>
<td><%= task.name %></td>
<td><%= task.due_date %></td>
</tr>
<% end %>
</table>

<table>
<% @tasks.each do |task| %>
    <% if task.due_date == Date.today %>
    <tr>
    <td><%=task.name%></td>
    <td><%= task.due_date.strftime("%m/%d") %></td>
    </tr>
  <% end %>
  <% end %>
</table>


<div class="form-group has-danger">
  <label class="form-label mt-4" for="inputInvalid">Invalid input</label>
  <input type="text" value="wrong value" class="form-control is-invalid" id="inputInvalid">
  <div class="invalid-feedback">Sorry, that username's taken. Try another?</div>
</div>

app/views/tasks/new.html.erb
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-1 me-5">
      <%= render "partials/sidebar"%>
    </div>
    <div class="col-md-5 ms-3 mt-2">
        <div class="card border-warning">  
            <h4 class="card-header text-decoration"><%= @category.name%></h4>
            <div class="card-body">
                <p class="card-title"><%= @category.description%></p>
            </div>
        </div>        
    </div>
    <div class="col-md-3 mt-2">
      <div class="card text-black bg-white">
        <h4 class="card-header text-decoration">Add New Task</h4>
          <div class="form-group ms-2 mt-2">
          <%= render "partials/task-error" %>
            <%= form_with scope: :task, model: [ @category, @task ], local: true do |f| %>
            <%= hidden_field_tag :category_id, @category.id %>
              <p>
                <%= f.text_field :name, placeholder: "Enter Task Name" %>
              </p>
              <p>
                <%= f.date_field :due_date, placeholder: "Pick a deadline" %>
              </p>
              <p>
                <%= submit_tag("Create Task") %>
              </p>
            <% end %> 
      </div>
    </div>          
  </div>
</div> <!-- container -->

app/views/tasks/show.html.erb
<h1> Show tasks details </h1>

    <p><%= @task.id %></p>
    <p><%= @task.name %></p>
    <p><%= @task.description %></p>
    <p><%= @task.due_date %></p>

<%= link_to 'Destroy', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %>